# Documentation about this file can be found here
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "11:00"
    labels:
      - "composer"
      - "dependencies"
    versioning-strategy: lockfile-only
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "11:00"
    labels:
      - "dependencies"
      - "infrastructure"
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: "monthly"
      time: "11:00"
    labels:
      - "dependencies"
      - "submodules"