language: php

php:
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache/files

services:
  - mysql
  
env:
 global:
  - URL=http://192.168.2.99
  - DB_TYPE=pdo.mysql
  - DB_HOST=localhost
  - DB_USER=root
  - DB_PASS=
  - DB_PCONNECT=0
  - DB_NAME=icms
  - DB_CHARSET=utf8
  - DB_COLLATION=utf8_general_ci
  - DB_PREFIX=icms
  - DB_SALT=icms
  
install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS icms;'
  - composer install

script:
 - ./vendor/bin/phpunit ./tests/libraries/* --bootstrap tests/bootstrap.php
