language: php

os:
  - linux

cache:
  directories:
    - "$HOME/.composer/cache"

env:
  global:
    - DB_TYPE=pdo.mysql
    - DB_HOST=localhost
    - DB_USER=root
    - DB_PASS=
    - DB_PCONNECT=0
    - DB_NAME=icms
    - DB_CHARSET=utf8
    - DB_COLLATION=utf8_general_ci
    - DB_PREFIX=icms
    - DB_SALT=icms

stages:
  - validate
  - test

services:
  - mysql

install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS icms;'
  - travis_retry composer install --no-progress --no-interaction

jobs:
  include:
    - stage: validate
      php: 7.2
      script:
        - composer validate
    - stage: test
      php: 7.2
      script:
        - composer test
      after_script:
        - ./vendor/bin/test-reporter --coverage-report=./storage/log/clover.xml
    - stage: test
      php: 7.3
      script:
        - composer test
