language: php

os:
  - linux

cache:
  directories:
    - "$HOME/.composer/cache"

env:
  global:
    - DB_TYPE=pdo.mysql
    - DB_HOST=localhost
    - DB_USER=root
    - DB_PASS=
    - DB_PCONNECT=0
    - DB_NAME=icms
    - DB_CHARSET=utf8
    - DB_COLLATION=utf8_general_ci
    - DB_PREFIX=icms
    - DB_SALT=icms

stages:
  - validate
  - test

services:
  - mysql

install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS icms;'
  - travis_retry composer install --no-progress --no-interaction

jobs:
  include:
    - stage: validate
      php: 7.2
      script:
        - composer validate
    - stage: test
      php: 7.2
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - composer test
      after_script:
        - mv ./storage/log/clover.xml ./clover.xml
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT --coverage-input-type clover
    - stage: test
      php: 7.3
      script:
        - composer test