files:
  - source: /htdocs/language/english/mail_template/*
    translation: /htdocs/language/%two_letters_code%/mail_template/%file_name%
  - source: /htdocs/language/english/*
    translation: /htdocs/language/%two_letters_code%/%file_name%
  - source: /htdocs/install/language/english/*
    translation: /htdocs/install/language/%two_letters_code%/%file_name%