name: After push to any main branch

on:
  push:
    branches:
      - 1.*
      - 2.*

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update_wiki:
    name: Updating wiki...
    runs-on: ubuntu-latest
    steps:
      - name: Checkouting main code...
        uses: actions/checkout@v3
      - name: Updating wiki...
        uses: impresscms-dev/phpdocs-wiki-update-action@v2.2
        with:
          wiki_github_update_token: ${{secrets.WIKI_GITHUB_UPDATE_TOKEN}}
          wiki_github_update_user: ${{secrets.WIKI_GITHUB_UPDATE_USER}}
          engine: clean/phpdoc-md
          class_root_namespace: ImpressCMS
          include: ImpressCMS\**