on:
  - push

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 1
      matrix:
        operating-system:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        php-versions:
          - 7.2
          - 7.3
          - 7.4
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: icms
          MYSQL_DATABASE: icms
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: curl gd PDO json mbstring pcre session
          ini-values: post_max_size=256M
      - name: Check PHP Version
        run: php -v
      - name: Verify MySQL connection
        run: |
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -picms -e "SHOW DATABASES"
      - name: Cache PHP dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}
      - name: Composer install
        uses: php-actions/composer@v1.0.0
        with:
          args: install --no-dev --no-interaction
      - name: PHPUnit tests
        uses: php-actions/phpunit@v1.0.0
        env:
          DB_TYPE: pdo.mysql
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASS: icms
          DB_PCONNECT: 0
          DB_NAME: icms
          DB_CHARSET: utf8
          DB_COLLATION: utf8_general_ci
          DB_PREFIX: icms
          DB_SALT: icms
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
        with:
          config: ./tests/configuration.xml
          memory: 256M